// ------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion: 14.0.0.0
//  
//     Änderungen an dieser Datei können fehlerhaftes Verhalten verursachen und gehen verloren, wenn
//     der Code neu generiert wird.
// </auto-generated>
// ------------------------------------------------------------------------------

namespace CVB.NET.DataAccess.Sql.T4Queries.Queries.Table
{
    using System.Linq;
    using Model.SubModels;
    using Utils;

    /// <summary>
    /// Class to produce the template output
    /// </summary>
#line 1 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Table\CreateTableQuery.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class CreateTableQuery : CVB.NET.TextTemplating.Runtime.Base.QueryTemplateBase<ITableDescription>
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
#line 3 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Table\CreateTableQuery.tt"
/*Imports*/

#line default
#line hidden
            this.Write("\r\n");

#line 10 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Table\CreateTableQuery.tt"
/*Create Table*/

#line default
#line hidden

#line 11 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Table\CreateTableQuery.tt"
            if (Description.Columns.Any())
            {
#line default
#line hidden
                this.Write("\t\tCREATE TABLE [");

#line 13 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Table\CreateTableQuery.tt"
                this.Write(this.ToStringHelper.ToStringWithCulture(Description.Schema));

#line default
#line hidden
                this.Write("].[");

#line 13 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Table\CreateTableQuery.tt"
                this.Write(this.ToStringHelper.ToStringWithCulture(Description.Table));

#line default
#line hidden
                this.Write("]\r\n\t\t(\r\n\t\t ");

#line 15 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Table\CreateTableQuery.tt"
                foreach (IColumnDescription columnDescription in Description.Columns)
                {
#line default
#line hidden
                    this.Write("\t\t\t\t[");

#line 17 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Table\CreateTableQuery.tt"
                    this.Write(this.ToStringHelper.ToStringWithCulture(columnDescription.Name));

#line default
#line hidden
                    this.Write("] ");

#line 17 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Table\CreateTableQuery.tt"
                    this.Write(this.ToStringHelper.ToStringWithCulture(columnDescription.Type));

#line default
#line hidden
                    this.Write(" ");

#line 17 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Table\CreateTableQuery.tt"
                    if (!columnDescription.AllowNull)
                    {
                        Write("NOT");
                    }

#line default
#line hidden
                    this.Write(" NULL,\r\n\t\t ");

#line 18 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Table\CreateTableQuery.tt"
                }

#line default
#line hidden
                this.Write("\t\t);\r\n");

#line 20 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Table\CreateTableQuery.tt"
            }

#line default
#line hidden

#line 21 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Table\CreateTableQuery.tt"
/*Set Primary Keys*/

#line default
#line hidden

#line 22 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Table\CreateTableQuery.tt"
            if (Description.OrmTypeMetaDataInfoView.TablePrimaryKeyDescriptions.Any())
            {
#line default
#line hidden
                this.Write("\t\tALTER TABLE [");

#line 24 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Table\CreateTableQuery.tt"
                this.Write(this.ToStringHelper.ToStringWithCulture(Description.Schema));

#line default
#line hidden
                this.Write("].[");

#line 24 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Table\CreateTableQuery.tt"
                this.Write(this.ToStringHelper.ToStringWithCulture(Description.Table));

#line default
#line hidden
                this.Write("] ADD CONSTRAINT [PK___TABLE_");

#line 24 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Table\CreateTableQuery.tt"
                this.Write(this.ToStringHelper.ToStringWithCulture(Description.Table));

#line default
#line hidden
                this.Write("]\r\n\t\t\tPRIMARY KEY \r\n\t\t\t(\r\n\t\t\t\t");

#line 27 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Table\CreateTableQuery.tt"
                this.Write(this.ToStringHelper.ToStringWithCulture(SqlQueryUtils.GetSeperatedColumnNames(Description.OrmTypeMetaDataInfoView.TablePrimaryKeyDescriptions, ", ", true)));

#line default
#line hidden
                this.Write("\r\n\t\t\t);\r\n");

#line 29 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Table\CreateTableQuery.tt"
            }

#line default
#line hidden
            return this.GenerationEnvironment.ToString();
        }
    }

#line default
#line hidden
}