// ------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion: 14.0.0.0
//  
//     Änderungen an dieser Datei können fehlerhaftes Verhalten verursachen und gehen verloren, wenn
//     der Code neu generiert wird.
// </auto-generated>
// ------------------------------------------------------------------------------

namespace CVB.NET.DataAccess.Sql.T4Queries.Queries.Record
{
    using System.Collections.Generic;
    using Model;
    using Model.SubModels;
    using Utils;

    /// <summary>
    /// Class to produce the template output
    /// </summary>
#line 1 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Record\InsertRecordQuery.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class InsertRecordQuery : CVB.NET.TextTemplating.Runtime.Base.QueryTemplateBase<InsertRecordDescription>
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
#line 3 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Record\InsertRecordQuery.tt"
/*Imports*/

#line default
#line hidden
            this.Write("\r\n");

#line 12 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Record\InsertRecordQuery.tt"
/*Insert Values*/

#line default
#line hidden

#line 13 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Record\InsertRecordQuery.tt"
            foreach (KeyValuePair<string, List<ColumnValue>> tableColumnsPair in Description.TableValues)
            {
#line default
#line hidden
                this.Write("\t\tINSERT INTO [");

#line 15 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Record\InsertRecordQuery.tt"
                this.Write(this.ToStringHelper.ToStringWithCulture(Description.Schema));

#line default
#line hidden
                this.Write("].[");

#line 15 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Record\InsertRecordQuery.tt"
                this.Write(this.ToStringHelper.ToStringWithCulture(tableColumnsPair.Key));

#line default
#line hidden
                this.Write("]\r\n\t\t(\r\n\t\t\t");

#line 17 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Record\InsertRecordQuery.tt"
                this.Write(this.ToStringHelper.ToStringWithCulture(SqlQueryUtils.GetSeperatedColumnNames(tableColumnsPair.Value, ", ", true)));

#line default
#line hidden
                this.Write("\r\n\t\t)\r\n\t\tVALUES\r\n\t\t(\r\n\t\t\t");

#line 21 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Record\InsertRecordQuery.tt"
                this.Write(this.ToStringHelper.ToStringWithCulture(SqlQueryUtils.GetCommaSeperatedValues(tableColumnsPair.Value)));

#line default
#line hidden
                this.Write("\r\n\t\t);\r\n\r\n");

#line 24 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Record\InsertRecordQuery.tt"
            }

#line default
#line hidden
            return this.GenerationEnvironment.ToString();
        }
    }

#line default
#line hidden
}