// ------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion: 14.0.0.0
//  
//     Änderungen an dieser Datei können fehlerhaftes Verhalten verursachen und gehen verloren, wenn
//     der Code neu generiert wird.
// </auto-generated>
// ------------------------------------------------------------------------------

namespace CVB.NET.DataAccess.Sql.T4Queries.Queries.Record
{
    using System.Linq;
    using Model;
    using Model.SubModels;
    using Utils;

    /// <summary>
    /// Class to produce the template output
    /// </summary>
#line 1 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Record\SelectRecordQuery.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class SelectRecordQuery : CVB.NET.TextTemplating.Runtime.Base.QueryTemplateBase<SelectRecordDescription>
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
#line 3 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Record\SelectRecordQuery.tt"
/*Imports*/

#line default
#line hidden

#line 11 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Record\SelectRecordQuery.tt"
/*Select Values*/
            string firstTable = Description.Tables.First();


#line default
#line hidden
            this.Write("  \r\n\r\n");

#line 15 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Record\SelectRecordQuery.tt"
            if (Description.Tables.Count > 1)
            {
                Description.Tables.Remove(firstTable);

#line default
#line hidden
                this.Write("                                                      ");

#line 17 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Record\SelectRecordQuery.tt"
                /* Miss out the comma if there are no values*/

#line default
#line hidden
                this.Write("\t\tSELECT ");

#line 18 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Record\SelectRecordQuery.tt"
                this.Write(this.ToStringHelper.ToStringWithCulture(SqlQueryUtils.GetJoinPrimaryKeys(Description.Keys, "T1")));

#line default
#line hidden
                this.Write("\r\n\t\t");

#line 19 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Record\SelectRecordQuery.tt"
                if (Description.Values.Any())
                {
#line default
#line hidden
                    this.Write(", ");

#line 19 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Record\SelectRecordQuery.tt"
                    this.Write(this.ToStringHelper.ToStringWithCulture(SqlQueryUtils.GetSeperatedColumnNames(Description.Values, ", ", true)));

#line default
#line hidden

#line 19 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Record\SelectRecordQuery.tt"
                }

#line default
#line hidden
                this.Write("\t\t  FROM [");

#line 20 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Record\SelectRecordQuery.tt"
                this.Write(this.ToStringHelper.ToStringWithCulture(Description.Schema));

#line default
#line hidden
                this.Write("].[");

#line 20 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Record\SelectRecordQuery.tt"
                this.Write(this.ToStringHelper.ToStringWithCulture(firstTable));

#line default
#line hidden
                this.Write("] as T1\r\n\t\t");

#line 21 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Record\SelectRecordQuery.tt"
                int i = 2;
                foreach (string table in Description.Tables)
                {
#line default
#line hidden
                    this.Write("\t\t\tINNER JOIN [");

#line 24 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Record\SelectRecordQuery.tt"
                    this.Write(this.ToStringHelper.ToStringWithCulture(Description.Schema));

#line default
#line hidden
                    this.Write("].[");

#line 24 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Record\SelectRecordQuery.tt"
                    this.Write(this.ToStringHelper.ToStringWithCulture(table));

#line default
#line hidden
                    this.Write("] as T");

#line 24 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Record\SelectRecordQuery.tt"
                    this.Write(this.ToStringHelper.ToStringWithCulture(i.ToString()));

#line default
#line hidden
                    this.Write(" ON \r\n\t\t\r\n\t\t\t");

#line 26 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Record\SelectRecordQuery.tt"
                    ColumnValue lastKey = Description.Keys.Last();
                    ColumnValue firstKey = Description.Keys.First();
                    foreach (ColumnValue primaryKey in Description.Keys)
                    {
                        if (primaryKey != lastKey && primaryKey != firstKey)
                        {
                            Write(" AND ");
                        }

#line default
#line hidden
                        this.Write("\t\t\t\t\t\t\tT");

#line 34 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Record\SelectRecordQuery.tt"
                        this.Write(this.ToStringHelper.ToStringWithCulture(i.ToString()));

#line default
#line hidden
                        this.Write(".[");

#line 34 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Record\SelectRecordQuery.tt"
                        this.Write(this.ToStringHelper.ToStringWithCulture(primaryKey.Name));

#line default
#line hidden
                        this.Write("] = T1.[");

#line 34 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Record\SelectRecordQuery.tt"
                        this.Write(this.ToStringHelper.ToStringWithCulture(primaryKey.Name));

#line default
#line hidden
                        this.Write("]\r\n\t\t\t\t\t");

#line 35 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Record\SelectRecordQuery.tt"
                    }

#line default
#line hidden
                    this.Write("\r\n\t\t\t\r\n\t\t\t");

#line 38 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Record\SelectRecordQuery.tt"
                    i++;
                }

#line default
#line hidden
                this.Write("\t\tWHERE ");

#line 40 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Record\SelectRecordQuery.tt"
                this.Write(this.ToStringHelper.ToStringWithCulture(SqlQueryUtils.MakeSqlCausalityChain("T1", Description.Keys, LogicalOperator.And)));

#line default
#line hidden
                this.Write("\r\n");

#line 42 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Record\SelectRecordQuery.tt"
            }
            else
            {
#line default
#line hidden
                this.Write("\t\tSELECT * ");

#line 45 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Record\SelectRecordQuery.tt"
/*= SqlQueryUtils.GetJoinPrimaryKeys(Description.Keys, firstTable) */

#line default
#line hidden
                this.Write("\t\t");

#line 46 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Record\SelectRecordQuery.tt"
                if (Description.Values.Any())
                {
#line default
#line hidden
                    this.Write(", ");

#line 46 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Record\SelectRecordQuery.tt"
                    this.Write(this.ToStringHelper.ToStringWithCulture(SqlQueryUtils.GetSeperatedColumnNames(Description.Values, ", ", true)));

#line default
#line hidden

#line 46 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Record\SelectRecordQuery.tt"
                }

#line default
#line hidden
                this.Write("\t\tFROM [");

#line 47 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Record\SelectRecordQuery.tt"
                this.Write(this.ToStringHelper.ToStringWithCulture(Description.Schema));

#line default
#line hidden
                this.Write("].[");

#line 47 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Record\SelectRecordQuery.tt"
                this.Write(this.ToStringHelper.ToStringWithCulture(firstTable));

#line default
#line hidden
                this.Write("]\r\n\t\tWHERE ");

#line 48 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Record\SelectRecordQuery.tt"
                this.Write(this.ToStringHelper.ToStringWithCulture(SqlQueryUtils.MakeSqlCausalityChain(firstTable, Description.Keys, LogicalOperator.And)));

#line default
#line hidden
                this.Write("\r\n");

#line 49 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Record\SelectRecordQuery.tt"
            }

#line default
#line hidden
            return this.GenerationEnvironment.ToString();
        }
    }

#line default
#line hidden
}