// ------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion: 14.0.0.0
//  
//     Änderungen an dieser Datei können fehlerhaftes Verhalten verursachen und gehen verloren, wenn
//     der Code neu generiert wird.
// </auto-generated>
// ------------------------------------------------------------------------------

namespace CVB.NET.DataAccess.Sql.T4Queries.Queries.Record
{
    using Model.Base;

    /// <summary>
    /// Class to produce the template output
    /// </summary>
#line 1 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Record\WriteQueryHeader.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class WriteQueryHeader : CVB.NET.TextTemplating.Runtime.Base.QueryTemplateBase<SchemaScopedQueryDescription>
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
#line 3 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Record\WriteQueryHeader.tt"
/*Imports*/

#line default
#line hidden

#line 12 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Record\WriteQueryHeader.tt"
/*Target Database*/

#line default
#line hidden
            this.Write("USE [");

#line 13 "G:\$projects\CVB.NET.Solution\src\CVB.NET.DataAccess.Sql\src\T4Queries\Queries\Record\WriteQueryHeader.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Description.Database));

#line default
#line hidden
            this.Write("];\r\n\r\nset xact_abort on\r\n\r\nBEGIN TRAN writeTransaction\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }

#line default
#line hidden
}